### ISSUE TITLE
Bad documentation causes issues when deploying.

### ISSUE THREAD

**Issue by gothrek22** [1Password/op-scim-helm#116]
Hi, most of the details in the template doesn't impact this issue, the only important thing would be the chart version which is 2.9.3.

The issue itself is that you need to set `credentialsVolume: false` if you want to use `credentialsSecrets`. Else it generates the template as in the screenshot below
![image](https://user-images.githubusercontent.com/1223127/215145409-9a27b8ab-8826-4f07-8ace-69abd0564418.png)

**Comment by juris** [comment]
It's better to set `credentialsVolume: null` to avoid warnings like these
```
coalesce.go:220: warning: cannot overwrite table with non table for op-scim-bridge.scim.credentialsVolume (map[accessModes:[ReadWriteOnce] files:map[scimsessionFile:scimsession workspaceCredentialsFile:workspace-credentials.json workspaceSettingsFile:workspace-settings.json] resources:map[requests:map[storage:1Gi]]])
coalesce.go:220: warning: cannot overwrite table with non table for op-scim-bridge.scim.credentialsVolume (map[accessModes:[ReadWriteOnce] files:map[scimsessionFile:scimsession workspaceCredentialsFile:workspace-credentials.json workspaceSettingsFile:workspace-settings.json] resources:map[requests:map[storage:1Gi]]])
```

**Comment by grellyd** [comment]
Thanks folks for the input. We were looking to start to address these concerns in https://github.com/1Password/op-scim-helm/pull/121/. Notable, [the two are now mutually exclusive](https://github.com/1Password/op-scim-helm/pull/121/files#diff-43c7abc4fb3baed4c3197c7ba26277c775c8882111ab37f0d8e8a50b27e17ef8R1-R3).

Does that fully mitigate your issue?

**Comment by gothrek22** [comment]
Yep.
