### ISSUE TITLE
Support for Multi-Arch Docker Images 

### ISSUE THREAD

**Issue by thiago-juro** [1Password/op-scim-helm#133]
### Summary
Currently 1password/scim image supports only OS/arch of type linux/amd64 .
It would be great to support multiple architectures, in particular linux/arm64 , as ARM processors are widely used.

**Comment by kevinfalting** [comment]
Hey @thiago-juro 👋 as of [`2.9.0`](https://app-updates.agilebits.com/product_history/SCIM#v209002), `arm64` architecture is supported. 🎉

I'll close this issue, but feel free to comment if you have any further questions. ✌️
