### ISSUE TITLE
SCIM bridge fails to start if tlsDomain is not set to null.

### ISSUE THREAD

**Issue by gothrek22** [1Password/op-scim-helm#134]
Newest version of the chart (2.10.5), newest version of the scim bridge (2.8.4).

I've set values.yml as below:
![image](https://github.com/1Password/op-scim-helm/assets/1223127/013552d0-50ab-4386-9f45-43231201f75b)

In theory this should set the OP_TLS_DOMAIN env var to `null` which disables the Let's Encrypt flow. Thing is, that due to condition here: https://github.com/1Password/op-scim-helm/blob/c052648748bc54081b2ae066b82bf7c976651579/charts/op-scim-bridge/templates/deployment.yaml#L139

null is evaluated to false, env is not rendered, scim bridge gets to CrashLoopBackoff, as it tries to do Let's Encrypt dance when it shouldn't.

So either:
- disable the check and always set the var with some sane default (i.e. null)
- change the behavior of the scim binary to NOT do the Let's Encrypt dance unless explicitly told to do so.

**Comment by av-sebastian** [comment]
+1, it took me too long to find what you reported here :s
