### ISSUE TITLE
Expand Supported Configuration Options

### ISSUE THREAD

**Issue by thatguygriff** [1Password/op-scim-helm#21]
The current helm chart lacks the flexibility expected for doing deployments into custom clusters. The chart should be updated to include configuration values (and secure defaults) for:

- Annotations
- Node Selector definitions
- Pod Affinity definitions
- Desired number of instances
- Image Pull Policy
- Image Pull Secrets
- Security Context
- Resource limits for the pod
- Persistent Volume Storage Class name
- Liveness and Readiness Probes
- Configurable Redis Hostname
- Ingress Options
    - Current default is load balancer
    - Allow for ingress rules to be defined outside of this chart
- Configuration for TLS termination at Cluster ingress or Service
- Pod Tolerations
- Pod Disruption Budget

Examples of all these options can be seen in either the [Connect Helm Chart](https://github.com/1Password/connect-helm-charts/blob/main/charts/connect/templates/connect-deployment.yaml) or [this closed PR](https://github.com/1Password/op-scim-helm/pull/5/files#diff-90f606e14abf95fb254de2a35f6ef6b6bc5701ccb706444a60ca16e88e994d24)

**Comment by devillexio** [comment]
The changes for this are already turning into a sizeable PR. I created  a couple of new ticket for:
- ingress controller: #29
- TLS termination: #30
