### ISSUE TITLE
Add documentation to the Chart

### ISSUE THREAD

**Issue by thatguygriff** [1Password/op-scim-helm#24]
Currently there is no documentation in the chart. Documentation should include:

- Maintainer information
- Requirements of the Chart
- How to deploy the SCIM Bridge
- Supported Configuration Values (and their Default values)

See the [Connect Helm Chart for an example](https://github.com/1Password/connect-helm-charts/tree/main/charts/connect) or [this closed PR](https://github.com/1Password/op-scim-helm/pull/5/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

**Comment by devillexio** [comment]
This is related to #9.
