### ISSUE TITLE
Helm Repo Index file contains wrong release dates

### ISSUE THREAD

**Issue by zsoltion** [1Password/op-scim-helm#52]
The `index.yaml` file contains the wrong release date value for the older charts in the `created` element. These should represent the release date of each chart version. Currently all of them uses the same value.

**Comment by via-justa** [comment]
@devillexio it looks like the chart version is not updated and it's impossible to pull the latest chart changes.
Any chance you release a new version of the chart?

**Comment by devillexio** [comment]
Hi @via-justa. That is correct, we have been committing incremental improvements and fixes to the Helm chart, but there has not been a new SCIM bridge release in a while.

I'm pleased to report that we are working on a new release that will include these fixes and improvements. Unfortunately I cannot share an ETA, but it should be a few weeks and not months.

I'm going to leave this issue open for now as I'm not sure if we will be able to fix the index.yaml release dates in the next release.

I hope that helps!

**Comment by laughingman-hass** [comment]
This seems to be a symptom of helm's odd behavior with the `helm repo index --merge` command.

https://github.com/helm/helm/issues/4482#issuecomment-452013778 provides a workaround. Will update internal documentation with this.
