### ISSUE TITLE
Redis URL does not refer to in-cluster redis deployment

### ISSUE THREAD

**Issue by timfallmk** [1Password/op-scim-helm#53]
When deploying via helm and a custom name (or any name), and not setting the `scim.config.redisURL` value (the default), the pod expects to find the redis service at `1password-redis-master` and fails. [This value](https://github.com/1Password/op-scim-helm/blob/main/op-scim-bridge/templates/deployment.yaml#L111) should be set by the generated redis service name (to allow use of in-cluster dns) _unless_ overriden by the config value.

```shell
FTL failed to set up redis for SCIM bridge error="Network: (failed to NewRedisConnPool), cannot initialize connection: cannot connect to redis: dial tcp: lookup 1password-redis-master on 172.20.0.10:53: no such host" application=op-scim build=
│ 203011 function=GetCache version=2.3.1
```

As a general note, there seem to be a couple of places where the design of this chart makes such, or similar, assumptions (lets encrypt url, domain, etc.). These are usually anti-patterns for helm, since as much as can be autogenerated should be. Not throwing shade here, this is very helpful and much appreciated!

I'm happy to help with any re-design or cleanup needed to enhance this chart so it's zero touch!

**Comment by devillexio** [comment]
Hi @timfallmk. Thanks so much for logging this issue!

This chart is always a work in progress and forms the base for our Digital Ocean and Google Cloud Marketplace apps.

I know this might be asking a lot, but it would be amazing if you could submit a PR with your improvement suggestions. This will allow us to review the suggestions and hopefully apply many of them.

**Comment by timfallmk** [comment]
Yes, I've been pulling together a PR with a number of refactors and changes. I'll push that upstream as soon as it's ready.

I've run into some blocking troubles in trying to get the bridge to run at all, so I'd like to get it up and running before putting anything forward.
