### ISSUE TITLE
Redis: allow specifying tolerations

### ISSUE THREAD

**Issue by artyom-p** [1Password/op-scim-helm#85]
Please add support for tolerations on redis

**Comment by devillexio** [comment]
Hi @artyom-p. Thanks for submitting the issue.

We already do support tolerations on redis via it being exposed by the [bitnami/redis](https://github.com/bitnami/charts/tree/master/bitnami/redis) chart we depend on.

These options can be set via `redis.master.tolerations` as an example to override the tolerations of the redis master.

You can see configuration options via their documentation.

I'm going to close this issue for now, but feel free to reopen it.
