### ISSUE TITLE
Please use { Release.Name } instead of { Chart.Name } in default values

### ISSUE THREAD

**Issue by pniederlag** [1Password/op-scim-helm#88]
some (default) values use  { Chart.Name } as default. This causes troubles when using a different release-name than the Chart.Nam

Therfor I would suggest to use { Release.Name } as default instead of { Chart.Name }

**Comment by devillexio** [comment]
Hi @pniederlag! Thanks for logging this issue.

I agree. This is a good suggestion. I'll look into implementing the change shortly.
